id: opecha:P003163
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS18856
  title: སྨན་རྫས་དོ་དམ་བྱེད་ཕྱོགས་སྐོར་གྱི་ཀྲུང་ཧྭ་མི་དམངས་སྤྱི་མཐུན་རྒྱལ་ཁབ་ཀྱི་བཅའ་ཁྲིམས།
  volume: ''
  author: ''
