id: P003163
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS18856
  title: སྨན་རྫས་དོ་དམ་བྱེད་ཕྱོགས་སྐོར་གྱི་ཀྲུང་ཧྭ་མི་དམངས་སྤྱི་མཐུན་རྒྱལ་ཁབ་ཀྱི་བཅའ་ཁྲིམས།
  author: ''
  volumes:
    c5ef634f298e4094a7da24bcbb870445:
      image_group_id: I8LS18858
      title: ''
      volume_number: 1
      total_pages: 74
